export const urlHeader = "http://localhost:7017/";
//order reducer
export const ORDER_LIST_FETCH_START = "ORDER_LIST_FETCH_START";
export const ORDER_DETAIL_FETCH_START = "ORDER_DETAIL_FETCH_START";
export const ORDER_UPDATE_START = "ORDER_UPDATE_START";
export const ORDER_CREATE_NEWLOG_START = "ORDER_CREATE_NEWLOG_START";

export const ORDER_LIST_FETCH_FAIL = "ORDER_LIST_FETCH_FAIL";
export const ORDER_UPDATE_FAIL = "ORDER_UPDATE_FAIL";
export const ORDER_DETAIL_FETCH_FAIL = "ORDER_DETAIL_FETCH_FAIL";
export const ORDER_CREATE_NEWLOG_FAIL = "ORDER_CREATE_NEWLOG_FAIL";

export const ORDER_LIST_FETCH_SUCCESS = "ORDER_LIST_FETCH_SUCCESS";
export const ORDER_DETAIL_FETCH_SUCCESS = "ORDER_DETAIL_FETCH_SUCCESS";
export const ORDER_UPDATE_SUCCESS = "ORDER_UPDATE_SUCCESS";
export const ORDER_CREATE_NEWLOG_SUCCESS = "ORDER_CREATE_NEWLOG_SUCCESS";

//auth reducer
export const AUTH_START = "AUTH_START";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
