export const urlHeader = "http://localhost:7017/";
//order reducer
export const ORDER_LIST_FETCH_START = "ORDER_LIST_FETCH_START";
export const ORDER_DETAIL_FETCH_START = "ORDER_DETAIL_FETCH_START";
export const ORDER_LIST_FETCH_FAIL = "ORDER_LIST_FETCH_FAIL";
export const ORDER_DETAIL_FETCH_FAIL = "ORDER_DETAIL_FETCH_FAIL";
export const ORDER_LIST_FETCH_SUCCESS = "ORDER_LIST_FETCH_SUCCESS";
